name: Theme Check
on: [push]
jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install theme-check
        run: npm install -g @shopify/theme-check
      - name: Run theme-check
        run: theme-check .